package Lessons.lesson14.exception.myException;

//public class MyExceptionDemo {
//    public static void main(String[] args) {
//        try {
//            compute(9);
//            compute(11);
//        } catch (MyException e){
//            System.err.println("Перехваченное исключение " + e);
//        }
//        System.out.println();
//        System.out.println("Дальнейший ход выполения в main");
//
//    }
//
//    public static void compute(int a){
//        System.out.println("Вызван метод compute c цифрой " + a);
//        if(a > 10){
//            throw new MyException(a, "trouble here");
//        }
//        System.out.println("Нормальное завершение программы");
//    }
//}
